##
## EPITECH PROJECT, 2019
## Makefile
## File description:
##  makefile
##

all :
		make -C ./generator/
		make -C ./solver/
clean:
		make clean -C ./solver/
		make clean -C ./generator/

fclean:
		make fclean -C ./solver/
		make fclean -C ./generator/

re:
		make re -C ./solver/
		make re -C ./generator/



